%% Generated by the Erlang ASN.1 compiler. Version: 5.0
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module X3-PROTOCOL.

-ifndef(_X3_PROTOCOL_HRL_).
-define(_X3_PROTOCOL_HRL_, true).

-record('IPPortInfo', {
  port,
  ipAddr
}).

-record('PayloadList_SEQOF', {
  mediaType,
  protocolType,
  payload
}).

-record('CreateLICTReq', {
  messageSerialNo,
  neID,
  icidValue,
  'cCC-ID',
  termAddr = asn1_NOVALUE
}).

-record('CreateLICTAck', {
  messageSerialNo,
  icidValue,
  'cCC-ID',
  x3TunnelCreateResult,
  x3TunnelFailureReason = asn1_NOVALUE
}).

-record('DeleteLICTReq', {
  messageSerialNo,
  icidValue,
  'cCC-ID',
  x3TunnelDeleteReason = asn1_NOVALUE
}).

-record('DeleteLICTAck', {
  messageSerialNo,
  icidValue,
  'cCC-ID'
}).

-record('CommunicationContentReport', {
  dataSerialNo,
  icidValue,
  'cCC-ID',
  dataDirect,
  payloadList
}).

-record('X3CheckStateReq', {
  neID
}).

-record('X3CheckStateAck', {
  neID
}).

-record('X3Interface', {
  protocolVersion,
  x3cmdMessage
}).

-endif. %% _X3_PROTOCOL_HRL_
